### ISSUE TITLE
pts/redis-1.2.0 fails to compile on ubuntu 20.10

### ISSUE THREAD

**Issue by nergdron** [phoronix-test-suite/test-profiles#178]
compilation fails with a lot of errors on multiple definition of SDS_NOINIT, here's the tail of the log:
```
/usr/bin/ld: t_stream.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: first defined here
/usr/bin/ld: lolwut.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: first defined here
/usr/bin/ld: lolwut5.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: multiple definition of `SDS_NOINIT'; quicklist.o:/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src/sds.h:37: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:219: redis-server] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/tessa/.phoronix-test-suite/installed-tests/pts/redis-1.2.0/redis-5.0.5/src'
make: *** [Makefile:6: all] Error 2
```

**Comment by michaellarabel** [comment]
Thanks, pts/redis-1.3.0 is now available that updates against the latest upstream Redis 6.0.9 and is building/running fine on Ubuntu 20.10.
