### ISSUE TITLE
pts/keydb-1.4.0 does not compile with GCC >= 13.1

### ISSUE THREAD

**Issue by tbe** [phoronix-test-suite/test-profiles#317]
KeyDB 6.3.2  fails during installation:

```
pts/keydb-1.4.0: ERROR: t_zset.cpp:2039:11: error: declaration of ‘zsetopsrc::_uT::_iterzset zsetopsrc::_uT::zset’ changes meaning of ‘zset’ [-Wchanges-meaning]
pts/keydb-1.4.0: The installer exited with a non-zero exit status.
```

This is fixed in [KeyDB-6.3.4](https://github.com/Snapchat/KeyDB/releases/tag/v6.3.4)
